sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch

install: "pip install -r requirements.txt; pip install tox-travis"
env:
  - TOXENV=pep8
  - TOXENV=coverage
script: tox
before_install:
  - pip install codecov
after_success:
  - codecov